import { expect, test } from '@playwright/test'

test('good actor completes an alternate checkout verification', async ({ page }) => {
  await page.goto('/shopper')
  await page.getByRole('button', { name: /verify with your bank/i }).click()
  await expect(page.getByText(/your order is moving/i)).toBeVisible()
  await expect(page.getByText(/does not add a fraud label/i)).toBeVisible()
})

test('impossible logistics is cured with a receipt image', async ({ page }) => {
  await page.goto('/shopper')
  await page.getByRole('tab', { name: /return handoff/i }).click()
  await page.locator('input[type=file]').setInputFiles({ name: 'staffed-receipt.png', mimeType: 'image/png', buffer: Buffer.from('fixture') })
  await page.getByRole('button', { name: /match receipt and continue/i }).click()
  await expect(page.getByText(/receipt matched return/i)).toBeVisible()
  await expect(page.getByText(/no adverse label was applied/i)).toBeVisible()
})

test('adverse return outcome requires a human and opens shopper appeal', async ({ page }) => {
  await page.goto('/merchant')
  await page.getByRole('button', { name: /deny requires reason/i }).click()
  await page.getByLabel(/reviewer rationale/i).fill('Complete capture protocol shows an empty container and no expected serial.')
  await page.getByRole('checkbox', { name: /i reviewed the native evidence/i }).check()
  await page.getByRole('button', { name: /record deny decision/i }).click()
  await expect(page.getByText(/contest window is open/i)).toBeVisible()
  await page.goto('/shopper')
  await page.getByRole('tab', { name: /contest & appeal/i }).click()
  await page.getByRole('button', { name: /submit for a second human review/i }).click()
  await expect(page.getByText(/your evidence is preserved/i)).toBeVisible()
})

test('narrow lifecycle exposes the full decision contract without horizontal page overflow', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name === 'desktop', 'Narrow-viewport assertion')
  await page.goto('/lifecycle')
  await expect(page.getByText('Native facts').first()).toBeVisible()
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 1)
  expect(overflow).toBe(false)
})

test('merchant scans a test label and receives a human-gated structured inspection', async ({ page }) => {
  await page.goto('/intake')
  await expect(page.locator('input[type=file][capture=environment]')).toHaveCount(1)
  await page.getByRole('button', { name: /run synthetic label tool/i }).click()
  await expect(page.getByText(/return record matched/i)).toBeVisible()
  await expect(page.locator('input[type=file][capture=environment]')).toHaveCount(2)
  await expect(page.getByRole('region', { name: /merchant policy snapshot/i })).toContainText('juniper-return-policy')
  await expect(page.getByRole('region', { name: /merchant policy snapshot/i })).toContainText('USD')
  await page.getByRole('button', { name: /analyze contents against order/i }).click()
  await expect(page.getByText(/schema-validated output/i)).toBeVisible()
  await expect(page.getByRole('heading', { name: /empty box/i })).toBeVisible()
  await expect(page.getByRole('region', { name: /inspection request and response/i })).toContainText('store: false')
  await page.getByRole('button', { name: /generate email preview/i }).click()
  await expect(page.getByText(/email preview/i)).toBeVisible()
  await expect(page.getByLabel(/approve as written draft binding/i)).toContainText('APPROVE_AS_WRITTEN')
  await expect(page.getByText(/unauthenticated display label only/i)).toBeVisible()
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 1)
  expect(overflow).toBe(false)
  await page.getByRole('checkbox', { name: /i reviewed the source images/i }).check()
  await page.getByRole('button', { name: /persist human review/i }).click()
  await expect(page.getByText(/review was not persisted/i)).toBeVisible()
  await expect(page.getByRole('button', { name: /queue test shopper message/i })).toBeDisabled()
})
